sources:
  friendly_name:
    type: filesystem
    directory: /my_images
  other_friendly_name:
    type: PACS
    aet:
    aem:
    port:
    ip:
    key:
      - 0008,0020="20250101"
      - 0008,0052="STUDY"
destination:
  files:
    directory: ~/some/directory
    compress: true
  metadata:
    dbType: MSSQL
    connectionString: mssql+pyodbc://scampi:scampi@host.docker.internal,1433/SCAMPI?driver=ODBC+Driver+18+for+SQL+Server&TrustServerCertificate=yes
    index: some_column
